# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20161226_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmclock',
            name='dayofweek',
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
    ]
