# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20161227_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
