# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_backupmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmclock',
            name='auto_stop_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backupmusic',
            name='backup_file',
            field=models.FileField(upload_to='backup_mp3'),
        ),
    ]
